# Generated by Django 2.2.10 on 2020-04-10 14:58

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', djongo.models.fields.ArrayField(model_container=api.models.Phone)),
                ('email', djongo.models.fields.ArrayField(model_container=api.models.Email)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(blank=True, max_length=100, null=True)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('search', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('topics', djongo.models.fields.ArrayField(model_container=api.models.StringField)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(default='')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
