export const STORY_REQUEST = 'STORY_REQUEST';
export const STORY_TITLES_FETCH_SUCCESS = 'STORY_TITLES_FETCH_SUCCESS';
export const STORY_FETCH_SUCCESS = 'STORY_FETCH_SUCCESS';
export const STORY_FAILURE = 'STORY_FAILURE';

