export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_FETCH_SUCCESS = 'CONTACT_FETCH_SUCCESS';
export const CONTACT_SEND_SUCCESS = 'CONTACT_SEND_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE';

