export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_SEND_SUCCESS = 'PROFILE_SEND_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

